version: '3.8'

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app 
    ports:
      - "8000:8000"
      #- "5678:5678"
    environment:
      - DATABASE_URL=postgresql://postgres:Storelink2024@db:5432/presenza
      - PYTHONPATH=/app
      - SMTP_PASSWORD=Stor&link@25!
      - SMTP_USERNAME=presenze@storelink.it
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend/presence-tracker
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "/api"
    volumes:
      - ./frontend/presence-tracker:/app
    environment:
      - VITE_API_URL=/api
    depends_on:
      - backend

  nginx:
    build:
      context: ./frontend/presence-tracker
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend

  db:
    image: postgres:15
    container_name: presenza_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Storelink2024
      - POSTGRES_DB=presenza
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
