"""Initial migration

Revision ID: cedfe0590522
Revises: 
Create Date: 2024-11-04 12:31:17.339412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedfe0590522'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('job_start_date', sa.Date(), nullable=False),
    sa.Column('full_time', sa.Boolean(), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('personal_email', sa.String(), nullable=True),
    sa.Column('work_email', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('personal_email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_work_email'), 'users', ['work_email'], unique=True)
    op.create_table('daily_presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('entry_time_morning', sa.Time(), nullable=True),
    sa.Column('exit_time_morning', sa.Time(), nullable=True),
    sa.Column('entry_time_afternoon', sa.Time(), nullable=True),
    sa.Column('exit_time_afternoon', sa.Time(), nullable=True),
    sa.Column('national_holiday', sa.Boolean(), nullable=True),
    sa.Column('weekend', sa.Boolean(), nullable=True),
    sa.Column('day_off', sa.Boolean(), nullable=True),
    sa.Column('time_off', sa.Time(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_presence_id'), 'daily_presence', ['id'], unique=False)
    op.create_table('hours_default',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_time_morning', sa.Time(), nullable=True),
    sa.Column('exit_time_morning', sa.Time(), nullable=True),
    sa.Column('entry_time_afternoon', sa.Time(), nullable=True),
    sa.Column('exit_time_afternoon', sa.Time(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hours_default_id'), 'hours_default', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hours_default_id'), table_name='hours_default')
    op.drop_table('hours_default')
    op.drop_index(op.f('ix_daily_presence_id'), table_name='daily_presence')
    op.drop_table('daily_presence')
    op.drop_index(op.f('ix_users_work_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
