"""alter tables

Revision ID: 8552ac160a21
Revises: a3e055be5c4b
Create Date: 2025-01-14 10:51:20.989172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8552ac160a21'
down_revision: Union[str, None] = 'a3e055be5c4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('national_holidays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_national_holidays_id'), 'national_holidays', ['id'], unique=False)
    op.create_table('admin_modified_presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('original_presence_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('modified_entry_time_morning', sa.Time(), nullable=True),
    sa.Column('modified_exit_time_morning', sa.Time(), nullable=True),
    sa.Column('modified_entry_time_afternoon', sa.Time(), nullable=True),
    sa.Column('modified_exit_time_afternoon', sa.Time(), nullable=True),
    sa.Column('modified_national_holiday', sa.Boolean(), nullable=True),
    sa.Column('modified_weekend', sa.Boolean(), nullable=True),
    sa.Column('modified_day_off', sa.Boolean(), nullable=True),
    sa.Column('modified_time_off', sa.Time(), nullable=True),
    sa.Column('modified_extra_hours', sa.Time(), nullable=True),
    sa.Column('modified_illness', sa.String(), nullable=True),
    sa.Column('modified_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_presence_id'], ['daily_presence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_modified_presence_id'), 'admin_modified_presence', ['id'], unique=False)
    op.add_column('daily_presence', sa.Column('illness', sa.String(), nullable=True))
    op.add_column('hours_default', sa.Column('submitted_by_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'hours_default', 'users', ['submitted_by_id'], ['id'])
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_constraint(None, 'hours_default', type_='foreignkey')
    op.drop_column('hours_default', 'submitted_by_id')
    op.drop_column('daily_presence', 'illness')
    op.drop_index(op.f('ix_admin_modified_presence_id'), table_name='admin_modified_presence')
    op.drop_table('admin_modified_presence')
    op.drop_index(op.f('ix_national_holidays_id'), table_name='national_holidays')
    op.drop_table('national_holidays')
    # ### end Alembic commands ###
