"""fix Forgein keys

Revision ID: a650843bbadc
Revises: e0c93f1c3d4d
Create Date: 2025-01-14 11:39:16.625954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a650843bbadc'
down_revision: Union[str, None] = 'e0c93f1c3d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
