"""fix one to one relationship

Revision ID: ac49e9ce7634
Revises: 7e3c9fe7e6d8
Create Date: 2025-01-15 14:36:01.937913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac49e9ce7634'
down_revision: Union[str, None] = '7e3c9fe7e6d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
