"""add relationships to Forgein keys

Revision ID: e0c93f1c3d4d
Revises: 8552ac160a21
Create Date: 2025-01-14 11:32:24.739859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0c93f1c3d4d'
down_revision: Union[str, None] = '8552ac160a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
